branch-defaults:
  master:
    environment: zachperkitny-prod
environment-defaults:
  zachperkitny-prod:
    branch: null
    repository: null
global:
  application_name: zachperkitny
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.4
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
