# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_remove_comment_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
    ]
