# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 22:32
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils.text import slugify
from blog.posts.models import Tag


def gen_slug(apps, schema_editor):
    for tag in Tag.objects.all():
        tag.slug = slugify(tag.word)
        print(tag.slug)
        tag.save()


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20170913_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.RunPython(gen_slug),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(editable=False, unique=True)
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='posts.Tag'),
        ),
    ]
